class systeminit::package::install {

$packages = [ "at",
"autoconf",
"automake",
"bind",
"bind-libs",
"bind-utils",
"bison",
"bzip2",
"bzip2-devel",
"cpp",
"cryptsetup-luks",
"curl",
"dstat",
"e2fsprogs-devel",
"e2fsprogs-libs",
"expat",
"expat-devel",
"expect",
"file",
"file-libs",
"flex",
"freetype",
"freetype-demos",
"freetype-devel",
"gcc",
"gcc-c++",
"gd",
"glib2",
"glib2-devel",
"glibc",
"glibc-common",
"glibc-devel",
"glibc-headers",
"iftop",
"iotop",
"irqbalance",
"keyutils-libs",
"keyutils-libs-devel",
"krb5-devel",
"krb5-libs",
"krb5-workstation",
"libcurl",
"libcurl-devel",
"libevent",
"libevent-devel",
"libidn-devel",
"libmcrypt",
"libmcrypt-devel",
"libpng",
"libpng-devel",
"libselinux",
"libselinux-devel",
"libsepol",
"libsepol-devel",
"libssh2",
"libtool-ltdl",
"libtool-ltdl-devel",
"libxml2",
"libxml2-devel",
"libxml2-python",
"libXpm",
"lrzsz",
"lsof",
"make",
"man",
"mhash",
"mlocate",
"ncurses",
"ncurses-devel",
"net-snmp",
"net-snmp-libs",
"nspr",
"nss",
"nss-sysinit",
"nss-util",
"ntp",
"openldap",
"openssh",
"openssh-clients",
"openssh-server",
"openssl",
"openssl-devel",
"pam-devel",
"pcre-devel",
"perl",
"perl-DBI",
"perl-devel",
"perl-ExtUtils-MakeMaker",
"perl-ExtUtils-ParseXS",
"perl-TermReadKey",
"perl-Test-Harness",
"perl-Time-HiRes",
"python-devel",
"rsync",
"screen",
"sudo",
"sysstat",
"tcl",
"telnet",
"traceroute",
"vim-common",
"vim-enhanced",
"vnstat",
"xz",
"xz-lzma-compat",
"zlib",
"zlib-devel",
"dos2unix",
"unix2dos",
"nc",
"smartmontools",
"mtr",
"kernel-devel",
"tcpdump",
"libmcrypt*",
"rpmforge-release.x86_64",
"yum-plugin-priorities",]

yumrepo { 'mcyw':
  baseurl        => "http://104.131.82.4/centos/6.5/x86_64",
  enabled        => "1",
  gpgcheck       => "0",
  descr          => "mcyw centos",
  priority       => "1"
}

package { $packages:
  ensure         => installed,
  require        => Yumrepo["mcyw"],
  allow_virtual => false,
}

package {"MegaCli.noarch":
  ensure         => installed,
  require        => Yumrepo["mcyw"],
  allow_virtual => false,
}

file {"/usr/bin/MegaCli64":
  ensure  => link,
  target  => "/opt/MegaRAID/MegaCli/MegaCli64",
  require => Package["MegaCli.noarch"],
}

include 'epel'
}